Repository martian58/keyforge, pull requests merged in 2025-05, with the labels that each got.

#1 Added a secure chat
  web/app.py
  web/migrations/versions/6185d0c0ce9d_.py
  web/migrations/versions/fb27e8471424_.py
  web/rsa.py
  web/static/css/output.css
  web/static/js/chat/chat.js
  web/static/js/mykeys.js
  web/static/js/register.js
  web/static/js/settings.js
  web/templates/chat/chat.html
  web/templates/dashboard.html
  web/templates/mykeys.html
  web/templates/navbar.html
  web/templates/settings.html
Labels: documentation

#3 Update the Readme file and finish the code
  desktop/src-tauri/icons/128x128.png
  desktop/src-tauri/icons/128x128@2x.png
  desktop/src-tauri/icons/32x32.png
  desktop/src-tauri/icons/Square107x107Logo.png
  desktop/src-tauri/icons/Square142x142Logo.png
  desktop/src-tauri/icons/Square150x150Logo.png
  desktop/src-tauri/icons/Square284x284Logo.png
  desktop/src-tauri/icons/Square30x30Logo.png
  desktop/src-tauri/icons/Square310x310Logo.png
  desktop/src-tauri/icons/Square44x44Logo.png
  desktop/src-tauri/icons/Square71x71Logo.png
  desktop/src-tauri/icons/Square89x89Logo.png
  desktop/src-tauri/icons/StoreLogo.png
  desktop/src-tauri/icons/icon.icns
  desktop/src-tauri/icons/icon.ico
  desktop/src-tauri/icons/icon.png
  web/README.md
Labels: documentation, enhancement

#4 Added Android Release
  desktop/src-tauri/gen/android/.editorconfig
  desktop/src-tauri/gen/android/.gitignore
  desktop/src-tauri/gen/android/app/.gitignore
  desktop/src-tauri/gen/android/app/build.gradle.kts
  desktop/src-tauri/gen/android/app/proguard-rules.pro
  desktop/src-tauri/gen/android/app/src/main/AndroidManifest.xml
  desktop/src-tauri/gen/android/app/src/main/java/com/keyforge/app/MainActivity.kt
  desktop/src-tauri/gen/android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  desktop/src-tauri/gen/android/app/src/main/res/drawable/ic_launcher_background.xml
  desktop/src-tauri/gen/android/app/src/main/res/layout/activity_main.xml
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  desktop/src-tauri/gen/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  desktop/src-tauri/gen/android/app/src/main/res/values-night/themes.xml
  desktop/src-tauri/gen/android/app/src/main/res/values/colors.xml
  desktop/src-tauri/gen/android/app/src/main/res/values/strings.xml
  desktop/src-tauri/gen/android/app/src/main/res/values/themes.xml
  desktop/src-tauri/gen/android/app/src/main/res/xml/file_paths.xml
  desktop/src-tauri/gen/android/build.gradle.kts
  desktop/src-tauri/gen/android/buildSrc/build.gradle.kts
  desktop/src-tauri/gen/android/buildSrc/src/main/java/com/keyforge/app/kotlin/BuildTask.kt
  desktop/src-tauri/gen/android/buildSrc/src/main/java/com/keyforge/app/kotlin/RustPlugin.kt
  desktop/src-tauri/gen/android/gradle.properties
  desktop/src-tauri/gen/android/gradle/wrapper/gradle-wrapper.jar
  desktop/src-tauri/gen/android/gradle/wrapper/gradle-wrapper.properties
  desktop/src-tauri/gen/android/gradlew
  desktop/src-tauri/gen/android/gradlew.bat
  desktop/src-tauri/gen/android/settings.gradle
  web/.env_example
Labels: enhancement

#5 Updated README.md file
  README.md
Labels: documentation

#8 Updated the index page
  web/templates/index.html
Labels: enhancement

#11 Add Explanations for RSA
  web/static/css/output.css
  web/static/js/chat/chat.js
  web/static/js/dashboard.js
  web/static/js/settings.js
Labels: documentation

#12 Update The README.md file
  README.md
Labels: documentation
